name: 'Slacklog action'
description: 'Send a changelog of recent PR to the Slack channel'
author: 'Evgeny Klimenchenko'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  SLACK_CLIENT_TOKEN:
    description: 'Slack client token to be able to post in the channel'
    required: true
  SLACK_CHANNEL_ID:
    description: 'Slack channel id'
    required: true
  ACTION_STATUS:
    description: 'Action status'
    required: true
  ACTION_WORKFLOW_NAME:
    description: 'Action name'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
